### ISSUE TITLE
Page Idea: Verse Generator

### ISSUE THREAD

**Issue by BekahT** [BekahT/BekahT.github.io#1]
### Verse Generator
- [x] Choose a set of Bible verses (inspirational)
- Arrange verses in an array.
- Can add verses with verseList.push
- [x] Pick random verse (number) from the array (0-X)
- Will change each time page is refreshed
- [x] Use calming/subdued colors
- [x] Make boxes adjust to contents

**Comment by yiqu** [comment]
Good idea.

**Comment by BekahT** [comment]
Use the overlapping boxes idea.

`<!DOCTYPE html>
<html>
<head>
<style>
*{
 box-sizing:border-box;
 }

h1 {
  border: 1px solid black;
  height: 200px;
  width: 500px;
  padding: 10px;
  position:relative;
  top: 20px;
  left: 50px;
  background:lightyellow;
  text-align:center;
  font-size:60px;
}
h2 {
  border: 1px solid black;
  height: 150px;
  width: 300px;
  padding: 10px;
  position:relative;
  bottom: 120px;
  left: 150px;
  background:lightgreen;
  text-align:center;
}
</style>
</head>
<body>

<h1>Jeremiah 41:10</h1>
<h2>For I know the plans I have for you says the Lord, plans to give you a hope and a future.</h2>

</body>
</html>
`

**Comment by BekahT** [comment]
### Verse List
- Isaiah 40:30-31  Even youths grow tired and weary, and young men stumble and fall; but those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint. 

- Isaiah 43:2 When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.

- Proverbs 18:10 The name of the LORD is a fortified tower; the righteous run to it and are safe.

- Psalm 120:1 I call on the LORD in my distress, and he answers me. 

- Psalm 31:24 Be strong and take heart, all you who hope in the LORD. 

- Proverbs 3:5-6 Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.

- 2 Corinthians 1:3-4 Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles, so that we can comfort those in any trouble with the comfort we ourselves receive from God. 

- Isaiah 41:10 So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand. 

- John 14:27 Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.

- John 16:33 I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.

- Psalm 46:1-3 God is our refuge and strength, an ever-present help in trouble. Therefore we will not fear, though the earth give way and the mountains fall into the heart of the sea, though its waters roar and foam and the mountains quake with their surging.

- 2 Timothy 1:7 For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline. 

- Psalm 16:8 I keep my eyes always on the LORD. With him at my right hand, I will not be shaken. 

- Psalm 55:22 Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken. 

- Psalm 34:8 Taste and see that the LORD is good; blessed is the one who takes refuge in him. 

- Romans 8:28 And we know that in all things God works for the good of those who love him, who have been called according to his purpose. 

- Romans 15:13  May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit. 

- Romans 8:38-39 For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord. 

- Lamentations 3:22-23 Because of the LORD’s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness. 

- 1 Corinthians 16:13 Be on your guard; stand firm in the faith; be courageous; be strong. 

- James 1:2-4 Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance. Let perseverance finish its work so that you may be mature and complete, not lacking anything. 

- Psalm 23:1 The LORD is my shepherd, I lack nothing. 

- 1 Corinthians 15:58 Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain. 

- Galatians 5:22-23 But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.

- Hebrews 12:14  Make every effort to live in peace with everyone and to be holy; without holiness no one will see the Lord. 

- 1 Peter 5:7 Cast all your anxiety on him because he cares for you. 

- 1 Thessalonians 5:15  Make sure that nobody pays back wrong for wrong, but always strive to do what is good for each other and for everyone else. 

- James 3:18 Peacemakers who sow in peace reap a harvest of righteousness. 

- Philippians 4:7 And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. 

- Proverbs 16:7 When the LORD takes pleasure in anyone’s way, he causes their enemies to make peace with them. 

- Romans 12:18 If it is possible, as far as it depends on you, live at peace with everyone. 

- Romans 14:19  Let us therefore make every effort to do what leads to peace and to mutual edification. 

- Psalm 34:14  Turn from evil and do good; seek peace and pursue it. 

- Isaiah 54:10 Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken nor my covenant of peace be removed,” says the LORD, who has compassion on you. 

- John 16:33 I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.

- Philippians 4:6-7 Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus. 

- Job 11:18-19 You will be secure, because there is hope; you will look about you and take your rest in safety. You will lie down, with no one to make you afraid, and many will court your favor. 

- Psalm 147:10-11  His pleasure is not in the strength of the horse, nor his delight in the legs of the warrior; the LORD delights in those who fear him, who put their hope in his unfailing love.

- Jeremiah 29:11 For I know the plans I have for you,” declares the LORD, “plans to prosper you and not to harm you, plans to give you hope and a future.
