### ISSUE TITLE
Use bootstrap in parts of my page

### ISSUE THREAD

**Issue by BekahT** [BekahT/BekahT.github.io#8]
### http://getbootstrap.com/getting-started/#examples

- [x] Nav bar fixed to top
- [x] Icon in nav bar
- [x] What I'm learning progress bars
- [x] Customize with my own CSS
- Include below in HTML file, make sure mine is last so it will override
```html
<head>
<link rel="stylesheet" type="text/css" href="bootstrap-3.3.7-dist/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="style.css">
</head>
```

- [x] Use icons from here: http://marcoceppi.github.io/bootstrap-glyphicons/
- Email =  icon-envelope
- GitHub = icon-github
- Projects = icon-briefcase

**Comment by yiqu** [comment]
would recommend put these in the <header> section

```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
```

**Comment by yiqu** [comment]
Example:

https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_button_styles&stacked=h
